version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
      - docker build -t nginx-sample .
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <account>.dkr.ecr.$AWS_REGION.amazonaws.com)
      - docker tag nginx-sample:latest <account>.dkr.ecr.$AWS_REGION.amazonaws.com/nginx-sample:latest
      - docker push <account>.dkr.ecr.$AWS_REGION.amazonaws.com/nginx-sample:latest
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
post_build:
  commands:
    - printf '[{"name":"nginx","imageUri":"%s"}]' <account>.dkr.ecr.$AWS_REGION.amazonaws.com/nginx-sample:latest > imagedefinitions.json
